app = "pmo-worker"
primary_region = "fra"  # Frankfurt

[build]
  builder = "dockerfile"

[env]

[deploy]
  release_command = ""

[[services]]
  internal_port = 8080
  processes = ["app"]

  [services.http_checks]
    enabled = false
